

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace BookLib.DataAccessLayer
{
	using DataModel;
	using System;
	using System.Data.Entity;
	using System.Data.Entity.Infrastructure;


	public partial class BookLibDBContainer : DbContext
{
    public BookLibDBContainer()
        : base("name=BookLibDBContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Book> Books { get; set; }

    public virtual DbSet<BookType> BookTypes { get; set; }

    public virtual DbSet<Status> Status { get; set; }

    public virtual DbSet<History> Histories { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

}

}

